"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OffscreenCanvasAdapter = exports.NumberFeaturesTile = exports.MetadataReference = exports.MetadataExtension = exports.MetadataDao = exports.Metadata = exports.MediaTable = exports.ImageUtils = exports.IconTable = exports.Icons = exports.IconCache = exports.HtmlCanvasAdapter = exports.GeoPackageValidate = exports.GeoPackageTileRetriever = exports.GeoPackageDataType = exports.GeoPackageConnection = exports.GeoPackageAPI = exports.GeoPackage = exports.GeometryData = exports.GeometryColumnsDao = exports.GeometryColumns = exports.GeometryType = exports.FeatureTiles = exports.FeatureTableStyles = exports.FeatureTableReader = exports.FeatureTableIndex = exports.FeatureTable = exports.FeatureStyles = exports.FeatureStyleExtension = exports.FeatureStyle = exports.FeaturePaint = exports.FeatureDrawType = exports.FeatureColumn = exports.Extension = exports.DublinCoreType = exports.DublinCoreMetadata = exports.DataColumnsDao = exports.DataColumns = exports.DataColumnConstraintsDao = exports.DataColumnConstraints = exports.CrsWktExtension = exports.Context = exports.ConstraintType = exports.Constraints = exports.Constraint = exports.ContentsIdDao = exports.ContentsDao = exports.CanvasKitCanvasAdapter = exports.Canvas = exports.BoundingBox = void 0;
exports.WKB = exports.WebPExtension = exports.UserTableReader = exports.UserTable = exports.UserRow = exports.UserMappingTable = exports.UserDao = exports.UserColumn = exports.TileUtilities = exports.TileTable = exports.TileScalingType = exports.TileScaling = exports.TileMatrixSet = exports.TileMatrix = exports.TileColumn = exports.TileBoundingBoxUtils = exports.TileCreator = exports.TableCreator = exports.StyleTable = exports.Styles = exports.SqljsAdapter = exports.StyleMappingTable = exports.SqliteQueryBuilder = exports.SqliteAdapter = exports.SpatialReferenceSystem = exports.SimpleAttributesTable = exports.ShadedFeaturesTile = exports.SchemaExtension = exports.setSqljsWasmLocateFile = exports.setCanvasKitWasmLocateFile = exports.RTreeIndexDao = exports.RTreeIndex = exports.RelatedTablesExtension = exports.ProjectionConstants = exports.Projection = exports.Paint = exports.OptionBuilder = void 0;
var boundingBox_1 = require("./lib/boundingBox");
Object.defineProperty(exports, "BoundingBox", { enumerable: true, get: function () { return boundingBox_1.BoundingBox; } });
var geoPackage_1 = require("./lib/geoPackage");
Object.defineProperty(exports, "GeoPackage", { enumerable: true, get: function () { return geoPackage_1.GeoPackage; } });
var contentsDao_1 = require("./lib/core/contents/contentsDao");
Object.defineProperty(exports, "ContentsDao", { enumerable: true, get: function () { return contentsDao_1.ContentsDao; } });
var contentsIdDao_1 = require("./lib/extension/contents/contentsIdDao");
Object.defineProperty(exports, "ContentsIdDao", { enumerable: true, get: function () { return contentsIdDao_1.ContentsIdDao; } });
var constraint_1 = require("./lib/db/table/constraint");
Object.defineProperty(exports, "Constraint", { enumerable: true, get: function () { return constraint_1.Constraint; } });
var constraints_1 = require("./lib/db/table/constraints");
Object.defineProperty(exports, "Constraints", { enumerable: true, get: function () { return constraints_1.Constraints; } });
var constraintType_1 = require("./lib/db/table/constraintType");
Object.defineProperty(exports, "ConstraintType", { enumerable: true, get: function () { return constraintType_1.ConstraintType; } });
var crsWkt_1 = require("./lib/extension/crsWkt");
Object.defineProperty(exports, "CrsWktExtension", { enumerable: true, get: function () { return crsWkt_1.CrsWktExtension; } });
var dataColumnConstraints_1 = require("./lib/dataColumnConstraints/dataColumnConstraints");
Object.defineProperty(exports, "DataColumnConstraints", { enumerable: true, get: function () { return dataColumnConstraints_1.DataColumnConstraints; } });
var dataColumnConstraintsDao_1 = require("./lib/dataColumnConstraints/dataColumnConstraintsDao");
Object.defineProperty(exports, "DataColumnConstraintsDao", { enumerable: true, get: function () { return dataColumnConstraintsDao_1.DataColumnConstraintsDao; } });
var dataColumns_1 = require("./lib/dataColumns/dataColumns");
Object.defineProperty(exports, "DataColumns", { enumerable: true, get: function () { return dataColumns_1.DataColumns; } });
var geoPackageDataType_1 = require("./lib/db/geoPackageDataType");
Object.defineProperty(exports, "GeoPackageDataType", { enumerable: true, get: function () { return geoPackageDataType_1.GeoPackageDataType; } });
var dataColumnsDao_1 = require("./lib/dataColumns/dataColumnsDao");
Object.defineProperty(exports, "DataColumnsDao", { enumerable: true, get: function () { return dataColumnsDao_1.DataColumnsDao; } });
var dublinCoreMetadata_1 = require("./lib/extension/relatedTables/dublinCoreMetadata");
Object.defineProperty(exports, "DublinCoreMetadata", { enumerable: true, get: function () { return dublinCoreMetadata_1.DublinCoreMetadata; } });
var dublinCoreType_1 = require("./lib/extension/relatedTables/dublinCoreType");
Object.defineProperty(exports, "DublinCoreType", { enumerable: true, get: function () { return dublinCoreType_1.DublinCoreType; } });
var extension_1 = require("./lib/extension/extension");
Object.defineProperty(exports, "Extension", { enumerable: true, get: function () { return extension_1.Extension; } });
var featureColumn_1 = require("./lib/features/user/featureColumn");
Object.defineProperty(exports, "FeatureColumn", { enumerable: true, get: function () { return featureColumn_1.FeatureColumn; } });
var featureDrawType_1 = require("./lib/tiles/features/featureDrawType");
Object.defineProperty(exports, "FeatureDrawType", { enumerable: true, get: function () { return featureDrawType_1.FeatureDrawType; } });
var featurePaint_1 = require("./lib/tiles/features/featurePaint");
Object.defineProperty(exports, "FeaturePaint", { enumerable: true, get: function () { return featurePaint_1.FeaturePaint; } });
var featureStyle_1 = require("./lib/extension/style/featureStyle");
Object.defineProperty(exports, "FeatureStyle", { enumerable: true, get: function () { return featureStyle_1.FeatureStyle; } });
var style_1 = require("./lib/extension/style");
Object.defineProperty(exports, "FeatureStyleExtension", { enumerable: true, get: function () { return style_1.FeatureStyleExtension; } });
var featureStyles_1 = require("./lib/extension/style/featureStyles");
Object.defineProperty(exports, "FeatureStyles", { enumerable: true, get: function () { return featureStyles_1.FeatureStyles; } });
var featureTable_1 = require("./lib/features/user/featureTable");
Object.defineProperty(exports, "FeatureTable", { enumerable: true, get: function () { return featureTable_1.FeatureTable; } });
var featureTableIndex_1 = require("./lib/extension/index/featureTableIndex");
Object.defineProperty(exports, "FeatureTableIndex", { enumerable: true, get: function () { return featureTableIndex_1.FeatureTableIndex; } });
var featureTableReader_1 = require("./lib/features/user/featureTableReader");
Object.defineProperty(exports, "FeatureTableReader", { enumerable: true, get: function () { return featureTableReader_1.FeatureTableReader; } });
var featureTableStyles_1 = require("./lib/extension/style/featureTableStyles");
Object.defineProperty(exports, "FeatureTableStyles", { enumerable: true, get: function () { return featureTableStyles_1.FeatureTableStyles; } });
var features_1 = require("./lib/tiles/features");
Object.defineProperty(exports, "FeatureTiles", { enumerable: true, get: function () { return features_1.FeatureTiles; } });
var geometryColumns_1 = require("./lib/features/columns/geometryColumns");
Object.defineProperty(exports, "GeometryColumns", { enumerable: true, get: function () { return geometryColumns_1.GeometryColumns; } });
var geometryColumnsDao_1 = require("./lib/features/columns/geometryColumnsDao");
Object.defineProperty(exports, "GeometryColumnsDao", { enumerable: true, get: function () { return geometryColumnsDao_1.GeometryColumnsDao; } });
var geometryData_1 = require("./lib/geom/geometryData");
Object.defineProperty(exports, "GeometryData", { enumerable: true, get: function () { return geometryData_1.GeometryData; } });
var geometryType_1 = require("./lib/features/user/geometryType");
Object.defineProperty(exports, "GeometryType", { enumerable: true, get: function () { return geometryType_1.GeometryType; } });
var api_1 = require("./lib/api");
Object.defineProperty(exports, "GeoPackageAPI", { enumerable: true, get: function () { return api_1.GeoPackageAPI; } });
var geoPackageConnection_1 = require("./lib/db/geoPackageConnection");
Object.defineProperty(exports, "GeoPackageConnection", { enumerable: true, get: function () { return geoPackageConnection_1.GeoPackageConnection; } });
var retriever_1 = require("./lib/tiles/retriever");
Object.defineProperty(exports, "GeoPackageTileRetriever", { enumerable: true, get: function () { return retriever_1.GeoPackageTileRetriever; } });
var geoPackageValidate_1 = require("./lib/validate/geoPackageValidate");
Object.defineProperty(exports, "GeoPackageValidate", { enumerable: true, get: function () { return geoPackageValidate_1.GeoPackageValidate; } });
var iconCache_1 = require("./lib/extension/style/iconCache");
Object.defineProperty(exports, "IconCache", { enumerable: true, get: function () { return iconCache_1.IconCache; } });
var icons_1 = require("./lib/extension/style/icons");
Object.defineProperty(exports, "Icons", { enumerable: true, get: function () { return icons_1.Icons; } });
var iconTable_1 = require("./lib/extension/style/iconTable");
Object.defineProperty(exports, "IconTable", { enumerable: true, get: function () { return iconTable_1.IconTable; } });
var imageUtils_1 = require("./lib/tiles/imageUtils");
Object.defineProperty(exports, "ImageUtils", { enumerable: true, get: function () { return imageUtils_1.ImageUtils; } });
var mediaTable_1 = require("./lib/extension/relatedTables/mediaTable");
Object.defineProperty(exports, "MediaTable", { enumerable: true, get: function () { return mediaTable_1.MediaTable; } });
var metadata_1 = require("./lib/metadata/metadata");
Object.defineProperty(exports, "Metadata", { enumerable: true, get: function () { return metadata_1.Metadata; } });
var metadataDao_1 = require("./lib/metadata/metadataDao");
Object.defineProperty(exports, "MetadataDao", { enumerable: true, get: function () { return metadataDao_1.MetadataDao; } });
var metadata_2 = require("./lib/extension/metadata");
Object.defineProperty(exports, "MetadataExtension", { enumerable: true, get: function () { return metadata_2.MetadataExtension; } });
var metadataReference_1 = require("./lib/metadata/reference/metadataReference");
Object.defineProperty(exports, "MetadataReference", { enumerable: true, get: function () { return metadataReference_1.MetadataReference; } });
var numberFeaturesTile_1 = require("./lib/tiles/features/custom/numberFeaturesTile");
Object.defineProperty(exports, "NumberFeaturesTile", { enumerable: true, get: function () { return numberFeaturesTile_1.NumberFeaturesTile; } });
var optionBuilder_1 = require("./lib/optionBuilder");
Object.defineProperty(exports, "OptionBuilder", { enumerable: true, get: function () { return optionBuilder_1.OptionBuilder; } });
var paint_1 = require("./lib/tiles/features/paint");
Object.defineProperty(exports, "Paint", { enumerable: true, get: function () { return paint_1.Paint; } });
var projection_1 = require("./lib/projection/projection");
Object.defineProperty(exports, "Projection", { enumerable: true, get: function () { return projection_1.Projection; } });
var projectionConstants_1 = require("./lib/projection/projectionConstants");
Object.defineProperty(exports, "ProjectionConstants", { enumerable: true, get: function () { return projectionConstants_1.ProjectionConstants; } });
var relatedTables_1 = require("./lib/extension/relatedTables");
Object.defineProperty(exports, "RelatedTablesExtension", { enumerable: true, get: function () { return relatedTables_1.RelatedTablesExtension; } });
var rtreeIndex_1 = require("./lib/extension/rtree/rtreeIndex");
Object.defineProperty(exports, "RTreeIndex", { enumerable: true, get: function () { return rtreeIndex_1.RTreeIndex; } });
var rtreeIndexDao_1 = require("./lib/extension/rtree/rtreeIndexDao");
Object.defineProperty(exports, "RTreeIndexDao", { enumerable: true, get: function () { return rtreeIndexDao_1.RTreeIndexDao; } });
var schema_1 = require("./lib/extension/schema");
Object.defineProperty(exports, "SchemaExtension", { enumerable: true, get: function () { return schema_1.SchemaExtension; } });
var shadedFeaturesTile_1 = require("./lib/tiles/features/custom/shadedFeaturesTile");
Object.defineProperty(exports, "ShadedFeaturesTile", { enumerable: true, get: function () { return shadedFeaturesTile_1.ShadedFeaturesTile; } });
var simpleAttributesTable_1 = require("./lib/extension/relatedTables/simpleAttributesTable");
Object.defineProperty(exports, "SimpleAttributesTable", { enumerable: true, get: function () { return simpleAttributesTable_1.SimpleAttributesTable; } });
var spatialReferenceSystem_1 = require("./lib/core/srs/spatialReferenceSystem");
Object.defineProperty(exports, "SpatialReferenceSystem", { enumerable: true, get: function () { return spatialReferenceSystem_1.SpatialReferenceSystem; } });
var sqliteQueryBuilder_1 = require("./lib/db/sqliteQueryBuilder");
Object.defineProperty(exports, "SqliteQueryBuilder", { enumerable: true, get: function () { return sqliteQueryBuilder_1.SqliteQueryBuilder; } });
var styleMappingTable_1 = require("./lib/extension/style/styleMappingTable");
Object.defineProperty(exports, "StyleMappingTable", { enumerable: true, get: function () { return styleMappingTable_1.StyleMappingTable; } });
var styles_1 = require("./lib/extension/style/styles");
Object.defineProperty(exports, "Styles", { enumerable: true, get: function () { return styles_1.Styles; } });
var styleTable_1 = require("./lib/extension/style/styleTable");
Object.defineProperty(exports, "StyleTable", { enumerable: true, get: function () { return styleTable_1.StyleTable; } });
var tableCreator_1 = require("./lib/db/tableCreator");
Object.defineProperty(exports, "TableCreator", { enumerable: true, get: function () { return tableCreator_1.TableCreator; } });
var tileBoundingBoxUtils_1 = require("./lib/tiles/tileBoundingBoxUtils");
Object.defineProperty(exports, "TileBoundingBoxUtils", { enumerable: true, get: function () { return tileBoundingBoxUtils_1.TileBoundingBoxUtils; } });
var tileColumn_1 = require("./lib/tiles/user/tileColumn");
Object.defineProperty(exports, "TileColumn", { enumerable: true, get: function () { return tileColumn_1.TileColumn; } });
var tileMatrix_1 = require("./lib/tiles/matrix/tileMatrix");
Object.defineProperty(exports, "TileMatrix", { enumerable: true, get: function () { return tileMatrix_1.TileMatrix; } });
var tileMatrixSet_1 = require("./lib/tiles/matrixset/tileMatrixSet");
Object.defineProperty(exports, "TileMatrixSet", { enumerable: true, get: function () { return tileMatrixSet_1.TileMatrixSet; } });
var tileScaling_1 = require("./lib/extension/scale/tileScaling");
Object.defineProperty(exports, "TileScaling", { enumerable: true, get: function () { return tileScaling_1.TileScaling; } });
var tileScalingType_1 = require("./lib/extension/scale/tileScalingType");
Object.defineProperty(exports, "TileScalingType", { enumerable: true, get: function () { return tileScalingType_1.TileScalingType; } });
var tileTable_1 = require("./lib/tiles/user/tileTable");
Object.defineProperty(exports, "TileTable", { enumerable: true, get: function () { return tileTable_1.TileTable; } });
var tileUtilities_1 = require("./lib/tiles/creator/tileUtilities");
Object.defineProperty(exports, "TileUtilities", { enumerable: true, get: function () { return tileUtilities_1.TileUtilities; } });
var userColumn_1 = require("./lib/user/userColumn");
Object.defineProperty(exports, "UserColumn", { enumerable: true, get: function () { return userColumn_1.UserColumn; } });
var userDao_1 = require("./lib/user/userDao");
Object.defineProperty(exports, "UserDao", { enumerable: true, get: function () { return userDao_1.UserDao; } });
var userMappingTable_1 = require("./lib/extension/relatedTables/userMappingTable");
Object.defineProperty(exports, "UserMappingTable", { enumerable: true, get: function () { return userMappingTable_1.UserMappingTable; } });
var userRow_1 = require("./lib/user/userRow");
Object.defineProperty(exports, "UserRow", { enumerable: true, get: function () { return userRow_1.UserRow; } });
var userTable_1 = require("./lib/user/userTable");
Object.defineProperty(exports, "UserTable", { enumerable: true, get: function () { return userTable_1.UserTable; } });
var userTableReader_1 = require("./lib/user/userTableReader");
Object.defineProperty(exports, "UserTableReader", { enumerable: true, get: function () { return userTableReader_1.UserTableReader; } });
var webp_1 = require("./lib/extension/webp");
Object.defineProperty(exports, "WebPExtension", { enumerable: true, get: function () { return webp_1.WebPExtension; } });
var wkb_1 = require("./lib/wkb");
Object.defineProperty(exports, "WKB", { enumerable: true, get: function () { return wkb_1.WKB; } });
var sqliteAdapter_1 = require("./lib/db/sqliteAdapter");
Object.defineProperty(exports, "SqliteAdapter", { enumerable: true, get: function () { return sqliteAdapter_1.SqliteAdapter; } });
var sqljsAdapter_1 = require("./lib/db/sqljsAdapter");
Object.defineProperty(exports, "SqljsAdapter", { enumerable: true, get: function () { return sqljsAdapter_1.SqljsAdapter; } });
var tileCreator_1 = require("./lib/tiles/creator/tileCreator");
Object.defineProperty(exports, "TileCreator", { enumerable: true, get: function () { return tileCreator_1.TileCreator; } });
var canvas_1 = require("./lib/canvas/canvas");
Object.defineProperty(exports, "Canvas", { enumerable: true, get: function () { return canvas_1.Canvas; } });
var canvasKitCanvasAdapter_1 = require("./lib/canvas/canvasKitCanvasAdapter");
Object.defineProperty(exports, "CanvasKitCanvasAdapter", { enumerable: true, get: function () { return canvasKitCanvasAdapter_1.CanvasKitCanvasAdapter; } });
var offscreenCanvasAdapter_1 = require("./lib/canvas/offscreenCanvasAdapter");
Object.defineProperty(exports, "OffscreenCanvasAdapter", { enumerable: true, get: function () { return offscreenCanvasAdapter_1.OffscreenCanvasAdapter; } });
var htmlCanvasAdapter_1 = require("./lib/canvas/htmlCanvasAdapter");
Object.defineProperty(exports, "HtmlCanvasAdapter", { enumerable: true, get: function () { return htmlCanvasAdapter_1.HtmlCanvasAdapter; } });
var context_1 = require("./lib/context/context");
Object.defineProperty(exports, "Context", { enumerable: true, get: function () { return context_1.Context; } });
context_1.Context.setupDefaultContext();
var setSqljsWasmLocateFile = sqljsAdapter_1.SqljsAdapter.setSqljsWasmLocateFile;
exports.setSqljsWasmLocateFile = setSqljsWasmLocateFile;
var setCanvasKitWasmLocateFile = canvasKitCanvasAdapter_1.CanvasKitCanvasAdapter.setCanvasKitWasmLocateFile;
exports.setCanvasKitWasmLocateFile = setCanvasKitWasmLocateFile;
//# sourceMappingURL=index.js.map