import globals from "globals";

/** @type {import('eslint').Linter.Config[]} */
export default [
    {
        languageOptions: {
            globals: {
                // Browser globals
                ...globals.browser,

                // Your custom globals
                atob: "readonly",
                BasiGX: "readonly",
                btoa: "readonly",
                D3Util: "readonly",
                download: "readonly",
                echarts: "readonly",
                Ext: "readonly",
                GeoExt: "readonly",
                GeoPackage: "readonly",
                GeoStyler: "readonly",
                GeoStylerGeoJsonParser: "readonly",
                MapboxStyleParser: "readonly",
                GeoStylerOpenlayersParser: "readonly",
                GeoStylerQGISParser: "readonly",
                GeoStylerSLDParser: "readonly",
                html2canvas: "readonly",
                jsts: "readonly",
                Koala: "readonly",
                moment: "readonly",
                ol: "readonly",
                Openrouteservice: "readonly",
                Papa: "readonly",
                proj4: "readonly",
                shpwrite: "readonly",
                turf: "readonly",
                WpsService: "readonly",
                InputGenerator: "readonly",
                OutputGenerator: "readonly",
                cptable: "readonly",
                shp: "readonly",
                JSZip: "readonly",
                maplibregl: "readonly",

                // Globals die in browser schon enthalten sind, aber hier spezifisch gesetzt
                cancelAnimationFrame: "readonly",
                d3: "readonly",
                File: "readonly",
                Image: "readonly",
                React: "readonly",
                ReactDOM: "readonly",
                requestAnimationFrame: "readonly",
                XMLSerializer: "readonly",
                sinon: "readonly",
                beforeEach: "readonly",
                afterEach: "readonly",
                describe: "readonly",
                it: "readonly",
                expect: "readonly",
                TestUtil: "readonly"
            },
            ecmaVersion: "latest",
            sourceType: "script"
        },

        rules: {
            "comma-dangle": ["error", "never"],
            "no-cond-assign": "error",
            "no-console": "error",
            "no-constant-condition": "error",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-dupe-args": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-empty-character-class": "error",
            "no-empty": "error",
            "no-ex-assign": "error",
            "no-extra-boolean-cast": "error",
            "no-extra-semi": "error",
            "no-func-assign": "error",
            "no-inner-declarations": "error",
            "no-invalid-regexp": "error",
            "no-irregular-whitespace": "error",
            "no-unsafe-negation": "error", // Ersatz für no-negated-in-lhs
            "no-obj-calls": "error",
            "no-regex-spaces": "error",
            "no-sparse-arrays": "error",
            "no-unreachable": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
            "no-unexpected-multiline": "error",

            "curly": "error",
            "eqeqeq": "error",
            "no-alert": "error",
            "no-caller": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-floating-decimal": "error",
            "no-implied-eval": "error",
            "no-multi-spaces": "warn",
            "no-multi-str": "error",
            "no-new-func": "error",
            "no-redeclare": "error",
            "no-self-compare": "error",
            "no-unused-expressions": "error",
            "no-with": "error",
            "radix": "error",
            "wrap-iife": "error",
            "strict": ["error", "never"],

            "no-catch-shadow": "error",
            "no-delete-var": "error",
            "no-shadow-restricted-names": "error",
            "no-shadow": "error",
            "no-undef": "error",
            "no-unused-vars": "error",
            "no-use-before-define": "error",

            "keyword-spacing": "warn",
            "key-spacing": ["warn", {
                "beforeColon": false,
                "afterColon": true
            }],
            "space-before-blocks": "warn",
            "space-before-function-paren": ["warn", "never"],
            "brace-style": ["warn", "1tbs"],
            "eol-last": "warn",
            "indent": ["error", 4, { "SwitchCase": 1 }],
            "quotes": ["error", "single"],
            "linebreak-style": ["error", "unix"],
            "no-mixed-spaces-and-tabs": "error",
            "no-nested-ternary": "off",
            "no-trailing-spaces": "error",
            "semi": ["error", "always"],
            "max-len": "off"
        }
    }
];
